config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'welcome/index'


  resources :contacts, :only => :create

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true
	validates :phone, presence: true
	validates :company, presence: true
	validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  invisible_captcha only: [:create, :update], honeypot: :subtitle
  
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:show, :edit, :update, :destroy]
  def check_user
    redirect_to root_path, notice: "Restricted area!" if !current_user
  end

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        UserMailer.contact_mail(@contact).deliver_later
        UserMailer.respond_mail(@contact).deliver_later
        format.html { redirect_to root_path, notice: 'Obrigado por entrar em contato, logo mais retornarei.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :email, :company, :message)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@contact = Contact.new
  end


  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :contact_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :contact_company %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :contact_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Company</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.company %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Henrique Costa - Full Stack Developer</title>
        <meta name="description" content="">
        <link rel="icon" href="<%= asset_path('favicon.png') %>" type="image/x-icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Importando fonte "Source Sans Pro" - Regular, Light, Bold -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
        
        <%= csrf_meta_tags %>

	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>

	    <%= yield %>
<!-- 
	    <script src="js/jquery.js"></script>
        <script src="js/validate.js"></script>
        <script src="js/app.js"></script>
 -->
        <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
       <!--  <script>
            window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
            ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
        </script>
        <script src="https://www.google-analytics.com/analytics.js" async defer></script> -->
    
  	</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
	   
       <section id="banner">
       		<% flash.each do |key, value| %>
			  <%= content_tag :div, value, class: "flash #{key}" %>
			<% end %>
            <div class="container">
             
              <div class="menu">
                <%= image_tag "menu-roxo.png" %>
              </div>
              <h1>Henrique Costa</h1>
              <h2>Full Stack Web Developer</h2>
            </div>

       </section>

       <div class="head">
         <div class="container">
          <!--  <div class="menu">
             <%= image_tag "menu-branco.png" %>
           </div> -->
           <div class="title">Henrique Costa <span>Full Stack Web Developer</span></div>
           <!-- <button id="btn-contato">Entre em contato</button> -->
         </div>
       </div>

       <section id="sobre">
           <div class="container">
              <div class="foto">
                 <div class="pic">
                  <%= image_tag "picture.png" %>
                 </div>
                 <a href="tel:+5561999523424" class="tel"> <i class="fa fa-mobile"></i> (61) 9 9952-3424 </a>
                 <a href="mailto:contato@henriquecosta.com" class="mail"> <i class="fa fa-envelope"></i> contato@henriquecosta.com </a>
             </div>
               <div class="texto">
                   <p>Olá, meu nome é <span>Henrique Gonsalves Costa</span>, tenho 25 anos e moro em Brasília/DF. Sou Desenvolvedor Web há 4 anos. Possuo bastante experiência criação de sites e aplicações Web. Já tive experiência também com criação de Aplicativos Mobile e Prototipação de Soluções Web/Mobile.</p>
                   <p>Sou estudante de <span>Engenharia de Software</span> e vou me formar em 2019. </p>
                   <p>Gosto muito de empreender apesar de ainda não ter atingido o sucesso financeiro, consegui muito crescimento pessoal. Me considero uma pessoa de boas idéias e capacidade para ajudar a criar negócios e empresas.   Possuo experiência com Marketing Digital, pois trabalhei como <span>Desenvolvedor Web</span> por 3 anos em uma agência digital chamada <span><a target="_blank" href="http://www.agencialooknfeel.com.br">Look’n Feel</a></span>. Adquiri também conhecimentos em Redes Sociais, Search Engine Optimization (SEO), Landing Pages e Design.</p>
                   <p>Trabalhei por 3 meses como <span>Analista de BI Junior</span> na <span><a target="_blank" href="http://www.dwbrasil.com.br">DW BRASIL</a></span>, empresa parceira de <span><a target="_blank" href="http://www.ibm.com">IBM</a></span> especializada em Business Intelligence.</p>
                   <p>Atualmente estou trabalhando na <a target="_blank" href="http://www.aistech.com.br"><span>AIS Tecnologia de Informação</span></a> como <span>Desenvolvedor Back-end</span> atuando em apps como: <a href="http://www.aulaup.com.br/" target="_blank">AulaUP</a> e <a href="http://dokter.com.br/" target="_blank">Dokter</a></p>
               </div>

               

               
           </div>
       </section>


       <section id="habilidades">
           <div class="container">
               <h1>Habilidades</h1>

               <div class="hab frontend">
               		<div class="texto">
                       <h3>Desenvolvedor Front-end</h3>
                       <p>O desenvovimento front-end é basicamente transformar o design gráfico em código para que o navegador seja capaz de apresentar para o usuário. Para isso utilizo as mais renomadas ferramentas do mercado. Possuo experiência em melhorar o tempo de carregamento de páginas e adaptação de sites desktop para sites que funcionam em todos os dispositivos do mercado. Com isso o resultado é totalmente voltado para acessibilidade e performance.</p>
                   </div>
                   <div class="image">
             			<%= image_tag "frontend_icons.png" %>
                   </div>
                   
               </div>

               <div class="hab backend">
               		<div class="texto">
                       <h3>Desenvolvedor Back-end</h3>
                       <p>O desenvolvimento back-end é onde entra a programação da aplicação. É onde nos preocupamos com o funcionamento do sistema e armazenamento dos dados.  </p>
                       <p>Tenho experiência com: Express (NodeJS), Wordpress e Zend (PHP) e Ruby on Rails</p>
                   </div>
                   <div class="image">
                       <%= image_tag "backend_icons.png" %>
                   </div>
                   
               </div>

               <div class="hab mobile">
               		 <div class="texto">
                       <h3>Desenvolvedor de Aplicativos Mobile</h3>
                       <p>Desenvolvimento de Aplicativos Hibridos, permitindo funcionar em praticamente todos os modelos de smartphones do mercado. Para isso utilizo um framework Javascript chamado Ionic 2. Além do aplicativo possuo conhecimento para fazer a integração com um webserver e garantir a comunicação entre sistemas.</p>
                   </div>
                   <div class="image">
                       <%= image_tag "mobile_icons.png" %>
                   </div>
                  
               </div>

               <div class="hab database">
               		<div class="texto">
                       <h3>Banco de Dados</h3>
                       <p>Tenho capacidade de modelar de banco de dados para aplicações e adquiri conhecimento sobre modelagem dimensional, voltada para área de BI. Tenho também experiência em MongoDB, que é um banco de dados NOSQL.</p>
                   </div>
                   <div class="image">
                       <%= image_tag "database_icons.png" %>
                   </div>
                   
               </div>

                <div class="hab cognos">
                	<div class="texto">
                       <h3>IBM Cognos Analytics</h3>
                       <p>Criação de relatórios de BI interativos utilizando a ferramenta Cognos Analytics 11.0.6 e Cognos 10.2.2</p>
                   </div>
                   <div class="image">
                       <%= image_tag "cognos_icons.png" %>
                   </div>
                  
               </div>

               
               <div class="hab ux">
                	<div class="texto">
                       <h3>UI/UX Designer</h3>
                       <p>Tenho também capacidade de criar a parte gráfica das interfaces de sites e aplicativos. Utilizo para criação das interfaces o Photoshop e o Sketch. Além de somente criar a interface, faço um trabalho para entender o projeto e ter um resultado totalmente voltado para experiência do usuário.</p>
                   </div>
                   <div class="image">
                       <%= image_tag "ux_icons.png" %>
                   </div>
                  
               </div>

           </div>
       </section>

       <section id="portfolio">
           <div class="container">
               <h1>Portifólio</h1>

               <div class="works">
                    <a href="http://www.sensei.poker" target="_blank" class="work sensei">
                       <ul>
                           <li>Web Design</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Backend (Node.js)</li>
                           <li>Pagamento Online Recorrente</li>
                       </ul>
                    </a>
                    <a href="http://www.agencialooknfeel.com.br" target="_blank" class="work lnf">
                        <ul>
                           <li>Prototipação</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Wordpress</li>
                       </ul>
                    </a>
                    <a href="http://www.viaapia.com.br" target="_blank" class="work viaapia">
                       <ul>
                           <li>Prototipação</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Wordpress</li>
                       </ul>
                    </a>
                    <a href="http://www.pousadacamelot.com.br" target="_blank" class="work camelot">
                       <ul>
                           <li>Prototipação</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Wordpress</li>
                       </ul>
                    </a>
                    <a href="https://gentle-shelf-8994.herokuapp.com" target="_blank" class="work suabiblioteca">
                       <ul>
                           <li>Prototipação</li>
                           <li>FrontEnd Responsivo</li>
                       </ul>
                    </a>
                    <a href="http://catarata.visaoinstitutos.com.br" target="_blank" class="work visao">
                       <ul>
                           <li>Landing Pages</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Backend</li>
                           <li>Prototipação</li>
                       </ul>
                    </a>
                    <a href="http://www.ikhon.com.br" target="_blank" class="work ikhon">
                       <ul>
                           <li>Web Design</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Wordpress</li>
                       </ul>
                    </a>
                    <a href="http://www.vantago.com.br" target="_blank" class="work vantago">
                       <ul>
                           <li>Prototipação</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Backend (Wordpress/Zend Framework)</li>
                           <li>Aplicativo Mobile (Ionic.js)</li>
                       </ul>
                    </a>
                    <a href="http://www.institutoverbalize.com" target="_blank" class="work verbalize">
                       <ul>
                           <li>Prototipação</li>
                           <li>FrontEnd Responsivo</li>
                           <li>Wordpress</li>
                       </ul>
                    </a>
               </div>


           </div>
       </section>

        <section id="contato">
           <div class="container">
               <h1>Contato</h1>
               <h3>Gostou? Entre em contato.</h3>

               	<%= form_for @contact, url: {controller: "contacts", action: "create"} do |f| %>
					<%= f.label :name, 'Nome:' %>
					<%= f.text_field :name, :required => true %>

					<%= f.label :phone, 'Telefone:' %>
					<%= f.text_field :phone, :required => true %>

					<%= f.label :email, 'E-mail:' %>
					<%= f.text_field :email, :required => true %>

					<%= f.label :company, 'Empresa:' %>
					<%= f.text_field :company, :required => true %>

					<%= f.label :message, 'Mensagem:' %>
					<%= f.text_area :message, size: "60x12", :required => true %>

          <%= f.invisible_captcha :subtitle %>

					<%= f.submit "ENVIAR" %>
				<% end %>

           </div>
        </section>
        
       